// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ccsm/v1/import.proto (package ccsm.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ccsm/v1/import.proto.
 */
export const file_ccsm_v1_import: GenFile = /*@__PURE__*/
  fileDesc("ChRjY3NtL3YxL2ltcG9ydC5wcm90bxIHY2NzbS52MSJoChFJbXBvcnRhYmxlU2Vzc2lvbhISCgpzZXNzaW9uX2lkGAEgASgJEhQKDHByb2plY3RfcGF0aBgCIAEoCRINCgV0aXRsZRgDIAEoCRIaChJsYXN0X21lc3NhZ2VfYXRfbXMYBCABKAMiKgoVU2NhbkltcG9ydGFibGVSZXF1ZXN0EhEKCXJvb3RfcGF0aBgBIAEoCSJGChZTY2FuSW1wb3J0YWJsZVJlc3BvbnNlEiwKCHNlc3Npb25zGAEgAygLMhouY2NzbS52MS5JbXBvcnRhYmxlU2Vzc2lvbiIlChRHZXRSZWNlbnRDd2RzUmVxdWVzdBINCgVsaW1pdBgBIAEoBSIlChVHZXRSZWNlbnRDd2RzUmVzcG9uc2USDAoEY3dkcxgBIAMoCWIGcHJvdG8z");

/**
 * @generated from message ccsm.v1.ImportableSession
 */
export type ImportableSession = Message<"ccsm.v1.ImportableSession"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string project_path = 2;
   */
  projectPath: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: int64 last_message_at_ms = 4;
   */
  lastMessageAtMs: bigint;
};

/**
 * Describes the message ccsm.v1.ImportableSession.
 * Use `create(ImportableSessionSchema)` to create a new message.
 */
export const ImportableSessionSchema: GenMessage<ImportableSession> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_import, 0);

/**
 * @generated from message ccsm.v1.ScanImportableRequest
 */
export type ScanImportableRequest = Message<"ccsm.v1.ScanImportableRequest"> & {
  /**
   * @generated from field: string root_path = 1;
   */
  rootPath: string;
};

/**
 * Describes the message ccsm.v1.ScanImportableRequest.
 * Use `create(ScanImportableRequestSchema)` to create a new message.
 */
export const ScanImportableRequestSchema: GenMessage<ScanImportableRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_import, 1);

/**
 * @generated from message ccsm.v1.ScanImportableResponse
 */
export type ScanImportableResponse = Message<"ccsm.v1.ScanImportableResponse"> & {
  /**
   * @generated from field: repeated ccsm.v1.ImportableSession sessions = 1;
   */
  sessions: ImportableSession[];
};

/**
 * Describes the message ccsm.v1.ScanImportableResponse.
 * Use `create(ScanImportableResponseSchema)` to create a new message.
 */
export const ScanImportableResponseSchema: GenMessage<ScanImportableResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_import, 2);

/**
 * @generated from message ccsm.v1.GetRecentCwdsRequest
 */
export type GetRecentCwdsRequest = Message<"ccsm.v1.GetRecentCwdsRequest"> & {
  /**
   * @generated from field: int32 limit = 1;
   */
  limit: number;
};

/**
 * Describes the message ccsm.v1.GetRecentCwdsRequest.
 * Use `create(GetRecentCwdsRequestSchema)` to create a new message.
 */
export const GetRecentCwdsRequestSchema: GenMessage<GetRecentCwdsRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_import, 3);

/**
 * @generated from message ccsm.v1.GetRecentCwdsResponse
 */
export type GetRecentCwdsResponse = Message<"ccsm.v1.GetRecentCwdsResponse"> & {
  /**
   * @generated from field: repeated string cwds = 1;
   */
  cwds: string[];
};

/**
 * Describes the message ccsm.v1.GetRecentCwdsResponse.
 * Use `create(GetRecentCwdsResponseSchema)` to create a new message.
 */
export const GetRecentCwdsResponseSchema: GenMessage<GetRecentCwdsResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_import, 4);

