// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ccsm/v1/notify.proto (package ccsm.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ccsm/v1/notify.proto.
 */
export const file_ccsm_v1_notify: GenFile = /*@__PURE__*/
  fileDesc("ChRjY3NtL3YxL25vdGlmeS5wcm90bxIHY2NzbS52MSJFChZOb3RpZnlVc2VySW5wdXRSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSFwoPaWRlbXBvdGVuY3lfa2V5GAIgASgJIhkKF05vdGlmeVVzZXJJbnB1dFJlc3BvbnNlIkMKEE5vdGlmeUZsYXNoRXZlbnQSEgoKc2Vzc2lvbl9pZBgBIAEoCRIMCgRraW5kGAIgASgJEg0KBXRzX21zGAMgASgDIhoKGFN0cmVhbU5vdGlmeUZsYXNoUmVxdWVzdCJFChlTdHJlYW1Ob3RpZnlGbGFzaFJlc3BvbnNlEigKBWV2ZW50GAEgASgLMhkuY2NzbS52MS5Ob3RpZnlGbGFzaEV2ZW50YgZwcm90bzM");

/**
 * @generated from message ccsm.v1.NotifyUserInputRequest
 */
export type NotifyUserInputRequest = Message<"ccsm.v1.NotifyUserInputRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * ch02 §9: dedup key for marker append.
   *
   * @generated from field: string idempotency_key = 2;
   */
  idempotencyKey: string;
};

/**
 * Describes the message ccsm.v1.NotifyUserInputRequest.
 * Use `create(NotifyUserInputRequestSchema)` to create a new message.
 */
export const NotifyUserInputRequestSchema: GenMessage<NotifyUserInputRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_notify, 0);

/**
 * @generated from message ccsm.v1.NotifyUserInputResponse
 */
export type NotifyUserInputResponse = Message<"ccsm.v1.NotifyUserInputResponse"> & {
};

/**
 * Describes the message ccsm.v1.NotifyUserInputResponse.
 * Use `create(NotifyUserInputResponseSchema)` to create a new message.
 */
export const NotifyUserInputResponseSchema: GenMessage<NotifyUserInputResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_notify, 1);

/**
 * @generated from message ccsm.v1.NotifyFlashEvent
 */
export type NotifyFlashEvent = Message<"ccsm.v1.NotifyFlashEvent"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string kind = 2;
   */
  kind: string;

  /**
   * @generated from field: int64 ts_ms = 3;
   */
  tsMs: bigint;
};

/**
 * Describes the message ccsm.v1.NotifyFlashEvent.
 * Use `create(NotifyFlashEventSchema)` to create a new message.
 */
export const NotifyFlashEventSchema: GenMessage<NotifyFlashEvent> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_notify, 2);

/**
 * @generated from message ccsm.v1.StreamNotifyFlashRequest
 */
export type StreamNotifyFlashRequest = Message<"ccsm.v1.StreamNotifyFlashRequest"> & {
};

/**
 * Describes the message ccsm.v1.StreamNotifyFlashRequest.
 * Use `create(StreamNotifyFlashRequestSchema)` to create a new message.
 */
export const StreamNotifyFlashRequestSchema: GenMessage<StreamNotifyFlashRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_notify, 3);

/**
 * @generated from message ccsm.v1.StreamNotifyFlashResponse
 */
export type StreamNotifyFlashResponse = Message<"ccsm.v1.StreamNotifyFlashResponse"> & {
  /**
   * @generated from field: ccsm.v1.NotifyFlashEvent event = 1;
   */
  event?: NotifyFlashEvent | undefined;
};

/**
 * Describes the message ccsm.v1.StreamNotifyFlashResponse.
 * Use `create(StreamNotifyFlashResponseSchema)` to create a new message.
 */
export const StreamNotifyFlashResponseSchema: GenMessage<StreamNotifyFlashResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_notify, 4);

