// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ccsm/v1/session.proto (package ccsm.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ccsm/v1/session.proto.
 */
export const file_ccsm_v1_session: GenFile = /*@__PURE__*/
  fileDesc("ChVjY3NtL3YxL3Nlc3Npb24ucHJvdG8SB2Njc20udjEiLQoXU2V0U2Vzc2lvbkFjdGl2ZVJlcXVlc3QSEgoKc2Vzc2lvbl9pZBgBIAEoCSIaChhTZXRTZXNzaW9uQWN0aXZlUmVzcG9uc2UiOQoVU2V0U2Vzc2lvbk5hbWVSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSDAoEbmFtZRgCIAEoCSIYChZTZXRTZXNzaW9uTmFtZVJlc3BvbnNlIkUKEVNlc3Npb25TdGF0ZUV2ZW50EhIKCnNlc3Npb25faWQYASABKAkSDQoFc3RhdGUYAiABKAkSDQoFdHNfbXMYAyABKAMiNgoRU2Vzc2lvblRpdGxlRXZlbnQSEgoKc2Vzc2lvbl9pZBgBIAEoCRINCgV0aXRsZRgCIAEoCSJRChlTZXNzaW9uQ3dkUmVkaXJlY3RlZEV2ZW50EhIKCnNlc3Npb25faWQYASABKAkSEAoIZnJvbV9jd2QYAiABKAkSDgoGdG9fY3dkGAMgASgJIioKFFNlc3Npb25BY3RpdmF0ZUV2ZW50EhIKCnNlc3Npb25faWQYASABKAkiGwoZU3RyZWFtU2Vzc2lvblN0YXRlUmVxdWVzdCJHChpTdHJlYW1TZXNzaW9uU3RhdGVSZXNwb25zZRIpCgVldmVudBgBIAEoCzIaLmNjc20udjEuU2Vzc2lvblN0YXRlRXZlbnQiGwoZU3RyZWFtU2Vzc2lvblRpdGxlUmVxdWVzdCJHChpTdHJlYW1TZXNzaW9uVGl0bGVSZXNwb25zZRIpCgVldmVudBgBIAEoCzIaLmNjc20udjEuU2Vzc2lvblRpdGxlRXZlbnQiIwohU3RyZWFtU2Vzc2lvbkN3ZFJlZGlyZWN0ZWRSZXF1ZXN0IlcKIlN0cmVhbVNlc3Npb25Dd2RSZWRpcmVjdGVkUmVzcG9uc2USMQoFZXZlbnQYASABKAsyIi5jY3NtLnYxLlNlc3Npb25Dd2RSZWRpcmVjdGVkRXZlbnQiHgocU3RyZWFtU2Vzc2lvbkFjdGl2YXRlUmVxdWVzdCJNCh1TdHJlYW1TZXNzaW9uQWN0aXZhdGVSZXNwb25zZRIsCgVldmVudBgBIAEoCzIdLmNjc20udjEuU2Vzc2lvbkFjdGl2YXRlRXZlbnRiBnByb3RvMw");

/**
 * @generated from message ccsm.v1.SetSessionActiveRequest
 */
export type SetSessionActiveRequest = Message<"ccsm.v1.SetSessionActiveRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message ccsm.v1.SetSessionActiveRequest.
 * Use `create(SetSessionActiveRequestSchema)` to create a new message.
 */
export const SetSessionActiveRequestSchema: GenMessage<SetSessionActiveRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 0);

/**
 * @generated from message ccsm.v1.SetSessionActiveResponse
 */
export type SetSessionActiveResponse = Message<"ccsm.v1.SetSessionActiveResponse"> & {
};

/**
 * Describes the message ccsm.v1.SetSessionActiveResponse.
 * Use `create(SetSessionActiveResponseSchema)` to create a new message.
 */
export const SetSessionActiveResponseSchema: GenMessage<SetSessionActiveResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 1);

/**
 * @generated from message ccsm.v1.SetSessionNameRequest
 */
export type SetSessionNameRequest = Message<"ccsm.v1.SetSessionNameRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message ccsm.v1.SetSessionNameRequest.
 * Use `create(SetSessionNameRequestSchema)` to create a new message.
 */
export const SetSessionNameRequestSchema: GenMessage<SetSessionNameRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 2);

/**
 * @generated from message ccsm.v1.SetSessionNameResponse
 */
export type SetSessionNameResponse = Message<"ccsm.v1.SetSessionNameResponse"> & {
};

/**
 * Describes the message ccsm.v1.SetSessionNameResponse.
 * Use `create(SetSessionNameResponseSchema)` to create a new message.
 */
export const SetSessionNameResponseSchema: GenMessage<SetSessionNameResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 3);

/**
 * stream payloads
 *
 * @generated from message ccsm.v1.SessionStateEvent
 */
export type SessionStateEvent = Message<"ccsm.v1.SessionStateEvent"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string state = 2;
   */
  state: string;

  /**
   * @generated from field: int64 ts_ms = 3;
   */
  tsMs: bigint;
};

/**
 * Describes the message ccsm.v1.SessionStateEvent.
 * Use `create(SessionStateEventSchema)` to create a new message.
 */
export const SessionStateEventSchema: GenMessage<SessionStateEvent> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 4);

/**
 * @generated from message ccsm.v1.SessionTitleEvent
 */
export type SessionTitleEvent = Message<"ccsm.v1.SessionTitleEvent"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;
};

/**
 * Describes the message ccsm.v1.SessionTitleEvent.
 * Use `create(SessionTitleEventSchema)` to create a new message.
 */
export const SessionTitleEventSchema: GenMessage<SessionTitleEvent> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 5);

/**
 * @generated from message ccsm.v1.SessionCwdRedirectedEvent
 */
export type SessionCwdRedirectedEvent = Message<"ccsm.v1.SessionCwdRedirectedEvent"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string from_cwd = 2;
   */
  fromCwd: string;

  /**
   * @generated from field: string to_cwd = 3;
   */
  toCwd: string;
};

/**
 * Describes the message ccsm.v1.SessionCwdRedirectedEvent.
 * Use `create(SessionCwdRedirectedEventSchema)` to create a new message.
 */
export const SessionCwdRedirectedEventSchema: GenMessage<SessionCwdRedirectedEvent> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 6);

/**
 * @generated from message ccsm.v1.SessionActivateEvent
 */
export type SessionActivateEvent = Message<"ccsm.v1.SessionActivateEvent"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message ccsm.v1.SessionActivateEvent.
 * Use `create(SessionActivateEventSchema)` to create a new message.
 */
export const SessionActivateEventSchema: GenMessage<SessionActivateEvent> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 7);

/**
 * @generated from message ccsm.v1.StreamSessionStateRequest
 */
export type StreamSessionStateRequest = Message<"ccsm.v1.StreamSessionStateRequest"> & {
};

/**
 * Describes the message ccsm.v1.StreamSessionStateRequest.
 * Use `create(StreamSessionStateRequestSchema)` to create a new message.
 */
export const StreamSessionStateRequestSchema: GenMessage<StreamSessionStateRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 8);

/**
 * @generated from message ccsm.v1.StreamSessionStateResponse
 */
export type StreamSessionStateResponse = Message<"ccsm.v1.StreamSessionStateResponse"> & {
  /**
   * @generated from field: ccsm.v1.SessionStateEvent event = 1;
   */
  event?: SessionStateEvent | undefined;
};

/**
 * Describes the message ccsm.v1.StreamSessionStateResponse.
 * Use `create(StreamSessionStateResponseSchema)` to create a new message.
 */
export const StreamSessionStateResponseSchema: GenMessage<StreamSessionStateResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 9);

/**
 * @generated from message ccsm.v1.StreamSessionTitleRequest
 */
export type StreamSessionTitleRequest = Message<"ccsm.v1.StreamSessionTitleRequest"> & {
};

/**
 * Describes the message ccsm.v1.StreamSessionTitleRequest.
 * Use `create(StreamSessionTitleRequestSchema)` to create a new message.
 */
export const StreamSessionTitleRequestSchema: GenMessage<StreamSessionTitleRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 10);

/**
 * @generated from message ccsm.v1.StreamSessionTitleResponse
 */
export type StreamSessionTitleResponse = Message<"ccsm.v1.StreamSessionTitleResponse"> & {
  /**
   * @generated from field: ccsm.v1.SessionTitleEvent event = 1;
   */
  event?: SessionTitleEvent | undefined;
};

/**
 * Describes the message ccsm.v1.StreamSessionTitleResponse.
 * Use `create(StreamSessionTitleResponseSchema)` to create a new message.
 */
export const StreamSessionTitleResponseSchema: GenMessage<StreamSessionTitleResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 11);

/**
 * @generated from message ccsm.v1.StreamSessionCwdRedirectedRequest
 */
export type StreamSessionCwdRedirectedRequest = Message<"ccsm.v1.StreamSessionCwdRedirectedRequest"> & {
};

/**
 * Describes the message ccsm.v1.StreamSessionCwdRedirectedRequest.
 * Use `create(StreamSessionCwdRedirectedRequestSchema)` to create a new message.
 */
export const StreamSessionCwdRedirectedRequestSchema: GenMessage<StreamSessionCwdRedirectedRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 12);

/**
 * @generated from message ccsm.v1.StreamSessionCwdRedirectedResponse
 */
export type StreamSessionCwdRedirectedResponse = Message<"ccsm.v1.StreamSessionCwdRedirectedResponse"> & {
  /**
   * @generated from field: ccsm.v1.SessionCwdRedirectedEvent event = 1;
   */
  event?: SessionCwdRedirectedEvent | undefined;
};

/**
 * Describes the message ccsm.v1.StreamSessionCwdRedirectedResponse.
 * Use `create(StreamSessionCwdRedirectedResponseSchema)` to create a new message.
 */
export const StreamSessionCwdRedirectedResponseSchema: GenMessage<StreamSessionCwdRedirectedResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 13);

/**
 * @generated from message ccsm.v1.StreamSessionActivateRequest
 */
export type StreamSessionActivateRequest = Message<"ccsm.v1.StreamSessionActivateRequest"> & {
};

/**
 * Describes the message ccsm.v1.StreamSessionActivateRequest.
 * Use `create(StreamSessionActivateRequestSchema)` to create a new message.
 */
export const StreamSessionActivateRequestSchema: GenMessage<StreamSessionActivateRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 14);

/**
 * @generated from message ccsm.v1.StreamSessionActivateResponse
 */
export type StreamSessionActivateResponse = Message<"ccsm.v1.StreamSessionActivateResponse"> & {
  /**
   * @generated from field: ccsm.v1.SessionActivateEvent event = 1;
   */
  event?: SessionActivateEvent | undefined;
};

/**
 * Describes the message ccsm.v1.StreamSessionActivateResponse.
 * Use `create(StreamSessionActivateResponseSchema)` to create a new message.
 */
export const StreamSessionActivateResponseSchema: GenMessage<StreamSessionActivateResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_session, 15);

