// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ccsm/v1/settings.proto (package ccsm.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ccsm/v1/settings.proto.
 */
export const file_ccsm_v1_settings: GenFile = /*@__PURE__*/
  fileDesc("ChZjY3NtL3YxL3NldHRpbmdzLnByb3RvEgdjY3NtLnYxIhgKFkdldERlZmF1bHRNb2RlbFJlcXVlc3QiKAoXR2V0RGVmYXVsdE1vZGVsUmVzcG9uc2USDQoFbW9kZWwYASABKAliBnByb3RvMw");

/**
 * @generated from message ccsm.v1.GetDefaultModelRequest
 */
export type GetDefaultModelRequest = Message<"ccsm.v1.GetDefaultModelRequest"> & {
};

/**
 * Describes the message ccsm.v1.GetDefaultModelRequest.
 * Use `create(GetDefaultModelRequestSchema)` to create a new message.
 */
export const GetDefaultModelRequestSchema: GenMessage<GetDefaultModelRequest> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_settings, 0);

/**
 * @generated from message ccsm.v1.GetDefaultModelResponse
 */
export type GetDefaultModelResponse = Message<"ccsm.v1.GetDefaultModelResponse"> & {
  /**
   * @generated from field: string model = 1;
   */
  model: string;
};

/**
 * Describes the message ccsm.v1.GetDefaultModelResponse.
 * Use `create(GetDefaultModelResponseSchema)` to create a new message.
 */
export const GetDefaultModelResponseSchema: GenMessage<GetDefaultModelResponse> = /*@__PURE__*/
  messageDesc(file_ccsm_v1_settings, 1);

