import { defineConfig } from 'vitest/config';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

// ESM equivalent of __dirname — required because this file is loaded as ESM
// (`.mts`) so vitest's config loader can resolve ESM-only deps such as
// `std-env` (pulled in transitively by vitest 4.x / pino).
const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  resolve: {
    alias: {
      '@ccsm/proto-gen/v1': path.resolve(__dirname, 'gen/ts/ccsm/v1/index.ts'),
      '@ccsm/proto-gen': path.resolve(__dirname, 'gen/ts/index.ts'),
    },
  },
  test: {
    environment: 'jsdom',
    // BISECT iter1: first half (140 files) — investigating CI hang
    include: [
      'daemon/src/__tests__/control-socket-isolation.test.ts',
      'daemon/src/__tests__/dispatcher-wiring-smoke.test.ts',
      'daemon/src/__tests__/dispatcher.test.ts',
      'daemon/src/__tests__/shutdown-for-upgrade-probe.test.ts',
      'daemon/src/__tests__/supervisor-wiring.test.ts',
      'daemon/src/connect/__tests__/server.test.ts',
      'daemon/src/crash/__tests__/scrub.test.ts',
      'daemon/src/db/__tests__/boot-orchestrator.test.ts',
      'daemon/src/db/__tests__/ensure-data-dir.test.ts',
      'daemon/src/db/__tests__/lowercase-data-root.test.ts',
      'daemon/src/db/__tests__/migrate-v02-to-v03.test.ts',
      'daemon/src/db/__tests__/migration-events.test.ts',
      'daemon/src/db/__tests__/migration-gate-consumer.test.ts',
      'daemon/src/db/schema/__tests__/v0.3.test.ts',
      'daemon/src/envelope/__tests__/adapter.test.ts',
      'daemon/src/envelope/__tests__/base64url.test.ts',
      'daemon/src/envelope/__tests__/boot-nonce-precedence.test.ts',
      'daemon/src/envelope/__tests__/chunk-reassembly.test.ts',
      'daemon/src/envelope/__tests__/deadline-interceptor.test.ts',
      'daemon/src/envelope/__tests__/envelope.test.ts',
      'daemon/src/envelope/__tests__/hello-interceptor.test.ts',
      'daemon/src/envelope/__tests__/hmac.test.ts',
      'daemon/src/envelope/__tests__/metrics-interceptor.test.ts',
      'daemon/src/envelope/__tests__/migration-gate-interceptor.test.ts',
      'daemon/src/envelope/__tests__/protocol-version.test.ts',
      'daemon/src/envelope/__tests__/supervisor-rpcs.test.ts',
      'daemon/src/envelope/__tests__/trace-id-map.test.ts',
      'daemon/src/envelope/__tests__/trace-interceptor.test.ts',
      'daemon/src/handlers/__tests__/daemon-hello.test.ts',
      'daemon/src/handlers/__tests__/daemon-shutdown-for-upgrade.test.ts',
      'daemon/src/handlers/__tests__/daemon-shutdown.test.ts',
      'daemon/src/handlers/__tests__/drop-slowest.probe.test.ts',
      'daemon/src/handlers/__tests__/healthz.test.ts',
      'daemon/src/handlers/__tests__/no-handler-without-check.test.ts',
      'daemon/src/handlers/__tests__/pty-subscribe.test.ts',
      'daemon/src/handlers/__tests__/stats.test.ts',
      'daemon/src/lifecycle/__tests__/crash-loop-skip.test.ts',
      'daemon/src/lifecycle/__tests__/dev-parent-watchdog.test.ts',
      'daemon/src/lifecycle/__tests__/force-kill.test.ts',
      'daemon/src/lifecycle/__tests__/lockfile.test.ts',
      'daemon/src/lifecycle/__tests__/shutdownDrain.test.ts',
      'daemon/src/listeners/__tests__/listenerA.test.ts',
      'daemon/src/log/__tests__/log.test.ts',
      'daemon/src/marker/__tests__/reader.test.ts',
      'daemon/src/native/__tests__/index.test.ts',
      'daemon/src/native/__tests__/no-direct-native-import.test.ts',
      'daemon/src/pty/__tests__/drop-slowest.test.ts',
      'daemon/src/pty/__tests__/fanout-registry.test.ts',
      'daemon/src/pty/__tests__/from-boot-nonce-stamper.test.ts',
      'daemon/src/pty/__tests__/heartbeat-envelope-owner.test.ts',
      'daemon/src/pty/__tests__/lifecycle.test.ts',
      'daemon/src/pty/__tests__/pipe-acl.test.ts',
      'daemon/src/pty/__tests__/replay-burst-exemption.test.ts',
      'daemon/src/pty/__tests__/sigchld-parallel-waitpid.probe.test.ts',
      'daemon/src/pty/__tests__/sigchld-reaper.test.ts',
      'daemon/src/pty/__tests__/snapshot-interleave.probe.test.ts',
      'daemon/src/pty/__tests__/snapshot-semaphore.test.ts',
      'daemon/src/pty/__tests__/stream-dead-detector.test.ts',
      'daemon/src/pty/__tests__/stream-heartbeat-scheduler.test.ts',
      'daemon/src/pty/__tests__/win-jobobject.test.ts',
      'daemon/src/sockets/__tests__/control-socket.test.ts',
      'daemon/src/sockets/__tests__/cross-user-acl-probe.test.ts',
      'daemon/src/sockets/__tests__/data-socket.test.ts',
      'daemon/src/sockets/__tests__/peer-cred-verify.test.ts',
      'daemon/src/sockets/__tests__/runtime-root.test.ts',
      'electron/daemonClient/__tests__/bridgeTimeout.test.ts',
      'electron/daemonClient/__tests__/connectClient.test.ts',
      'electron/daemonClient/__tests__/controlClient.test.ts',
      'electron/daemonClient/__tests__/envelope.test.ts',
      'electron/daemonClient/__tests__/noFloatingCancellation.test.ts',
      'electron/daemonClient/__tests__/reconnectQueue.test.ts',
      'electron/daemonClient/__tests__/rpcClient.test.ts',
      'electron/daemonClient/__tests__/spawnOrAttach.test.ts',
      'electron/daemonClient/__tests__/streamHandleTable.test.ts',
      'electron/daemonClient/__tests__/surfaceRegistry.test.ts',
      'electron/ipc/__tests__/dbIpc.test.ts',
      'electron/ipc/__tests__/sessionIpcSecurity.test.ts',
      'electron/ipc/__tests__/utilityIpc.test.ts',
      'electron/ipc/__tests__/utilityIpcSecurity.test.ts',
      'electron/lifecycle/__tests__/singleInstance.test.ts',
      'electron/migration/__tests__/migration-failure-probe.test.ts',
      'electron/migration/__tests__/modal-driver.test.ts',
      'electron/migration/__tests__/modal-progress-probe.test.ts',
      'electron/notify/__tests__/badgeLabel.test.ts',
      'electron/notify/__tests__/badgePixels.test.ts',
      'electron/notify/__tests__/badgeStore.test.ts',
      'electron/notify/__tests__/notifyDecider.test.ts',
      'electron/notify/__tests__/runStateTracker.test.ts',
      'electron/notify/__tests__/titleStateClassifier.test.ts',
      'electron/notify/bootstrap/__tests__/installPipeline.test.ts',
      'electron/notify/sinks/__tests__/badgeSink.test.ts',
      'electron/notify/sinks/__tests__/flashSink.test.ts',
      'electron/notify/sinks/__tests__/pipeline.test.ts',
      'electron/notify/sinks/__tests__/toastSink.test.ts',
      'electron/prefs/__tests__/closeAction.test.ts',
      'electron/prefs/__tests__/crashConsent.test.ts',
      'electron/prefs/__tests__/crashReporting.test.ts',
      'electron/prefs/__tests__/notifyEnabled.test.ts',
      'electron/prefs/__tests__/userCwds.test.ts',
      'electron/ptyHost/__tests__/bufferSnapshot.test.ts',
      'electron/ptyHost/__tests__/claudeResolver.test.ts',
      'electron/ptyHost/__tests__/cwd-fallback.test.ts',
      'electron/ptyHost/__tests__/cwdResolver.test.ts',
      'electron/ptyHost/__tests__/dataFanout.test.ts',
      'electron/ptyHost/__tests__/detachReattach.test.ts',
      'electron/ptyHost/__tests__/entryFactory.test.ts',
      'electron/ptyHost/__tests__/import-resume-copy.test.ts',
      'electron/ptyHost/__tests__/ipcRegistrar.test.ts',
      'electron/ptyHost/__tests__/jsonlResolver.test.ts',
      'electron/ptyHost/__tests__/lifecycle.test.ts',
      'electron/ptyHost/__tests__/oscTitleSniffer.test.ts',
      'electron/ptyHost/__tests__/processKiller.test.ts',
      'electron/security/__tests__/ipcGuards.test.ts',
      'electron/sessionTitles/__tests__/deciders.test.ts',
      'electron/sessionTitles/__tests__/forgetSid.test.ts',
      'electron/sessionTitles/__tests__/index.test.ts',
      'electron/sessionTitles/__tests__/renameWriteback.integration.test.ts',
      'electron/sessionWatcher/__tests__/emitDecider.test.ts',
      'electron/sessionWatcher/__tests__/facade.test.ts',
      'electron/sessionWatcher/__tests__/fileSource.test.ts',
      'electron/sessionWatcher/__tests__/inference.test.ts',
      'electron/sessionWatcher/__tests__/pendingRenameFlusher.test.ts',
      'electron/sessionWatcher/__tests__/projectKey.test.ts',
      'electron/sessionWatcher/__tests__/stateEmitter.test.ts',
      'electron/sessionWatcher/__tests__/titleChanged.test.ts',
      'electron/sessionWatcher/__tests__/titleEmitter.test.ts',
      'electron/sessionWatcher/__tests__/unwatched.test.ts',
      'electron/shared/__tests__/claudePaths.test.ts',
      'electron/shared/__tests__/stateSavedBus.test.ts',
      'electron/updater/__tests__/verify.test.ts',
      'electron/window/__tests__/createWindow.test.ts',
      'installer/uninstall-helper-mac/__tests__/helper.test.ts',
      'installer/uninstall-helper/__tests__/helper.test.ts',
      'installer/uninstall-helper/__tests__/uninstall-hygiene.test.ts',
      'tests/App.hooks.test.tsx',
      'tests/after-sign.test.ts',
      'tests/agent-lifecycle-unfocused.test.ts',
      'tests/app-effects/useAgentEventBridge.test.tsx',
      'tests/app-effects/useCwdRedirectedBridge.test.tsx',
      'tests/app-effects/useDaemonHealthBridge.test.tsx',
    ],
    globals: true,
    setupFiles: ['tests/setup.ts'],
    // v8 coverage instrumentation roughly doubles test wall-clock under
    // jsdom, so the default 5s testTimeout starts to flake on slower
    // suites (e.g. shortcut-overlay-platform with multiple act/render
    // cycles). Bump to 15s globally — well below CI job timeout, and
    // leaves headroom for `npm run coverage`.
    testTimeout: 15000,
    // Tech-debt R6 (Task #802) — coverage tooling. Reporters cover both
    // human (text) and machine (json-summary, lcov) consumers; lcov is
    // what CI uploads as an artifact.
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json-summary', 'lcov'],
      include: ['src/**/*.{ts,tsx}', 'electron/**/*.ts'],
      exclude: [
        '**/__tests__/**',
        '**/*.test.{ts,tsx}',
        '**/*.d.ts',
        'tests/**',
        'scripts/**',
        'dist/**',
      ],
      // Initial roll-out — start lenient. Adjusted to current actuals
      // (see PR #802 body for measured numbers). Bump in follow-up tasks
      // as suites grow. Thresholds are NOT enforced in CI yet — the CI
      // job runs `npm run coverage` to produce lcov.info as an artifact
      // but does not fail on threshold misses for this initial roll-out.
      thresholds: {
        lines: 60,
        functions: 60,
        branches: 50,
        statements: 60,
      },
    },
  },
});
