// Sentry init wrapper. Phase 2 crash observability (spec §6, plan Task 7):
// per-surface DSN routing, build-time injection, `tags.surface = 'main'`.
//
// DSN resolution order (first non-empty wins):
//   1. process.env.SENTRY_DSN_MAIN — runtime override (operators, dev)
//   2. process.env.SENTRY_DSN      — legacy single-DSN env (backward compat)
//   3. buildInfo.sentryDsnMain     — baked at packaging time by
//                                    scripts/before-pack.cjs from
//                                    CCSM_SENTRY_DSN_MAIN secret
//
// When all three are empty / undefined / the literal `***REDACTED***`
// placeholder, init short-circuits → Sentry is off and OSS forks ship
// without ever phoning home (spec §6 OSS-fork leak prevention).
//
// Crash reporting is OFF by default unless the operator plugs in a DSN.
// We do NOT ship a hardcoded project DSN in the open-source repo; release
// CI populates the build-info file from a `release`-environment secret.
//
// `beforeSend` consults the user's opt-out preference at every send so the
// Settings toggle takes effect immediately.

import * as Sentry from '@sentry/electron/main';
import { app } from 'electron';
import { isCrashUploadAllowed, loadCrashConsent } from '../prefs/crashConsent';

const REDACTED = '***REDACTED***';

interface BuildInfo {
  sentryDsnMain?: string;
  sentryDsnDaemon?: string;
  sentryDsnRenderer?: string;
}

function loadBuildInfo(): BuildInfo {
  try {
    // Generated by scripts/before-pack.cjs at packaging time. Absent in dev /
    // local `npm run build` runs — try/catch swallows the require failure so
    // dev keeps booting with Sentry off.
    // eslint-disable-next-line @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports
    return require('../../dist/electron/build-info.js') as BuildInfo;
  } catch {
    return {};
  }
}

export function initSentry(): void {
  // Phase 4 consent gate: when the user has not explicitly opted in, do NOT
  // create the SDK client at all. This is the user's hard constraint —
  // `pending` (first run, no answer yet) and `opted-out` both block upload.
  // Local crash logs are unaffected (phase 1 collector writes regardless).
  const consent = loadCrashConsent();
  if (consent !== 'opted-in') {
    console.info(`[sentry] crash upload consent=${consent} — Sentry off for surface=main.`);
    return;
  }
  const buildInfo = loadBuildInfo();
  const envDsn = process.env.SENTRY_DSN_MAIN?.trim() || process.env.SENTRY_DSN?.trim() || '';
  const dsn = envDsn || (buildInfo.sentryDsnMain ?? '').trim();
  if (!dsn || dsn === REDACTED) {
    console.info('[sentry] no DSN for surface=main — crash reporting disabled.');
    return;
  }
  Sentry.init({
    dsn,
    release: app.getVersion(),
    environment: app.isPackaged ? 'prod' : 'dev',
    sendDefaultPii: false,
    initialScope: { tags: { surface: 'main' } },
    beforeSend(event) {
      try {
        if (!isCrashUploadAllowed()) return null;
      } catch {
        /* fall through, send anyway */
      }
      return event;
    },
  });
}
