// daemon/src/connect/interceptors/context-keys.ts — Connect context keys
// shared across the interceptor chain.
//
// Spec citations:
//   - docs/superpowers/specs/2026-05-01-v0.4-web-design.md ch05 §4 (line 1174):
//     transport-tag is a positive enum set by the listener, NEVER read from a
//     header. Untagged → fail-closed as remote-tcp.
//   - ch02 §8 row "Trace-id ULID per envelope" — per-request ULID propagated
//     via x-ccsm-trace-id header; daemon-side mirrors as a context key.
//
// Single Responsibility (producer):
//   - This module ONLY produces context-key handles. It does NOT decide.
//
// Why a separate module: every interceptor reads/writes these; pulling them
// into one source-of-truth file avoids a circular import between the chain
// composer (server.ts) and individual interceptor files.

import { createContextKey } from '@connectrpc/connect';

/**
 * Transport tag set by the listener at connection-accept time. NEVER read
 * from a request header — header-spoofing this value would defeat the
 * remote-vs-local JWT bypass (ch05 §4).
 *
 * Values:
 *   - `'local-pipe'`  — Unix socket / Windows named pipe (peer-cred trust)
 *   - `'remote-tcp'`  — TCP listener fronted by Cloudflare Tunnel (JWT trust)
 *
 * Untagged context (i.e. the key is absent) is treated as `'remote-tcp'` for
 * fail-closed safety by every downstream interceptor.
 */
export const transportTypeKey = createContextKey<'local-pipe' | 'remote-tcp' | undefined>(
  undefined,
  { description: 'data-socket transport tag (positive enum, set by listener)' },
);

/**
 * Per-request trace-id (ULID). Generated by the trace-id interceptor; pino
 * log lines on the daemon side include it for end-to-end correlation
 * (matches v0.3 envelope `x-ccsm-trace-id` semantics, ch02 §8 row "Trace-id ULID").
 */
export const traceIdKey = createContextKey<string>('', {
  description: 'per-request ULID trace-id',
});

/**
 * Per-request start timestamp (ms since epoch) stamped by the transport-tag
 * slot. Used to compute `durationMs` on reject logs.
 */
export const requestStartKey = createContextKey<number>(0, {
  description: 'per-request start ms (Date.now() at chain entry)',
});

/**
 * Resolve the effective transport tag for fail-closed downstream decisions.
 * Untagged collapses to `'remote-tcp'` (per ch05 §4).
 */
export function resolveTransportTag(
  raw: 'local-pipe' | 'remote-tcp' | undefined,
): 'local-pipe' | 'remote-tcp' {
  return raw === 'local-pipe' ? 'local-pipe' : 'remote-tcp';
}

/**
 * Convert raw context value to a log-friendly tag (preserves the "untagged"
 * distinction for diagnostics, unlike {@link resolveTransportTag} which
 * fail-closes for security).
 */
export function transportTagForLog(
  raw: 'local-pipe' | 'remote-tcp' | undefined,
): 'local-pipe' | 'remote-tcp' | 'untagged' {
  if (raw === 'local-pipe') return 'local-pipe';
  if (raw === 'remote-tcp') return 'remote-tcp';
  return 'untagged';
}
