// daemon/src/connect/server.ts — T05 Connect-RPC server scaffold for the
// daemon's data-socket. Dormant in this PR: no service handlers are
// registered (T06 lands the first one); JWT verification is a placeholder
// (T08 lands the real one).
//
// Spec citations (canonical):
//   - docs/superpowers/specs/2026-05-01-v0.4-web-design.md ch02 §1 (wire = Connect)
//   - …                                                    ch02 §6 (data socket = HTTP/2 + Connect; control socket stays envelope)
//   - …                                                    ch02 §8 (interceptor inheritances from v0.3)
//   - …                                                    ch05 §4 (JWT interceptor; transport-tag positive enum; fail-closed)
//   - …                                                    ch05 §5 (chain order lock: transport-tag → JWT → migration-gate → … → handler)
//
// Single Responsibility (producer / decider / sink):
//   - This module is the WIRING: it composes pure deciders (interceptors) into
//     a Connect router and exposes a Node HTTP/2 server lifecycle. It does NOT
//     own the migration-pending flag (caller injects `isMigrationPending`),
//     does NOT own JWT verification (T08 will replace the placeholder), does
//     NOT own session state.
//
// Coexistence with v0.3 envelope (per task brief):
//   The v0.3 envelope handler stays on the data socket for the duration of
//   the v0.4 cutover. This module exposes `attachSocket(socket, transportType)`
//   which the eventual data-socket integration (T12 + T19 wave) will call after
//   peeking the first bytes of a connection: HTTP/2 preface (`PRI * HTTP/2.0…`)
//   → route here; otherwise → route to the envelope dispatcher. In T05 the
//   coexistence wiring is NOT live; only this module's surface is shipped so
//   T06+ can target a stable API.

import * as http2 from 'node:http2';
import type { Duplex } from 'node:stream';
import {
  Code,
  ConnectError,
  type ConnectRouter,
  type Interceptor,
  createContextKey,
} from '@connectrpc/connect';
import {
  connectNodeAdapter,
  universalRequestFromNodeRequest,
} from '@connectrpc/connect-node';
import { ulid } from 'ulid';
import {
  createPeerCredInterceptor,
  listenerAPeerCredVerdictKey,
  type PeerCredInterceptorOptions,
  type PeerCredStash,
} from '../listeners/listenerA.js';

// ---------------------------------------------------------------------------
// Context keys (positive enums per ch05 §4 lock)
// ---------------------------------------------------------------------------

/**
 * Transport tag set by the listener at connection-accept time. NEVER read
 * from a request header — header-spoofing this value would defeat the
 * remote-vs-local JWT bypass (ch05 §4).
 *
 * Values:
 *   - `'local-pipe'`  — Unix socket / Windows named pipe (peer-cred trust)
 *   - `'remote-tcp'`  — TCP listener fronted by Cloudflare Tunnel (JWT trust)
 *
 * Untagged context (i.e. the key is absent) is treated as `'remote-tcp'` for
 * fail-closed safety by every downstream interceptor.
 */
export const transportTypeKey = createContextKey<'local-pipe' | 'remote-tcp' | undefined>(
  undefined,
  { description: 'data-socket transport tag (positive enum, set by listener)' },
);

/**
 * Handshake-completed flag. Set to `true` by the eventual `daemon.hello`
 * Connect-side bootstrap RPC (T06+ will land it). Pre-handshake, this key is
 * absent and the hello-gate interceptor rejects any request not on
 * {@link PRE_HANDSHAKE_ALLOWLIST}.
 */
export const helloAckKey = createContextKey<boolean>(false, {
  description: 'true once the per-connection daemon.hello handshake has succeeded',
});

/**
 * Per-request trace-id (ULID). Generated by the trace-id interceptor; pino
 * log lines on the daemon side include it for end-to-end correlation
 * (matches v0.3 envelope `x-ccsm-trace-id` semantics, ch02 §8 row "Trace-id ULID").
 */
export const traceIdKey = createContextKey<string>('', {
  description: 'per-request ULID trace-id',
});

// ---------------------------------------------------------------------------
// Hello-gate constants
// ---------------------------------------------------------------------------

/**
 * Connect error code returned when a non-allowlisted RPC arrives before
 * `daemon.hello` succeeded. Pinned as a constant so the handshake protocol
 * has a single source of truth (T06's hello handler will reference it; T08's
 * JWT scaffold will mirror it for the unauthenticated-token path).
 */
export const HELLO_REQUIRED_CODE = Code.Unauthenticated;

/**
 * Methods admitted before the per-connection handshake completes. Mirrors the
 * v0.3 envelope `helloInterceptor` allowlist (just `daemon.hello`) plus the
 * v0.4 `Ping` health probe per ch02 §7 ("v0.4 introduces a `Ping` RPC that
 * returns `{ daemonVersion, protoVersion }`; clients call it on connect").
 *
 * Method names are matched by the `method.name` field of the Connect request
 * (NOT the full `service/method` URL) to keep the allowlist stable across
 * any future service-name reshuffle.
 */
export const PRE_HANDSHAKE_ALLOWLIST: readonly string[] = ['DaemonHello', 'Ping'] as const;

const PRE_HANDSHAKE_ALLOWLIST_SET: ReadonlySet<string> = new Set(PRE_HANDSHAKE_ALLOWLIST);

// ---------------------------------------------------------------------------
// Interceptors
// ---------------------------------------------------------------------------

/**
 * Transport-tag interceptor (ch05 §4 / §5). In T05 this is a no-op pass-through
 * because the listener is responsible for setting `transportTypeKey` at the
 * `contextValues` factory in the Connect adapter (see `createConnectDataServer`
 * `attachSocket`). The interceptor is kept in the chain at position #0 so the
 * declared order is observable + unit-testable; T19 wave may extend it with
 * dev-mode validation that the tag is present.
 */
function createTransportTagInterceptor(): Interceptor {
  return (next) => async (req) => next(req);
}

/**
 * JWT interceptor — T05 PLACEHOLDER. Real verification lands in T08.
 *
 * Behavior in this PR:
 *   - `transportTypeKey === 'local-pipe'` → bypass (per ch05 §4 local-bypass rule).
 *   - Anything else (`'remote-tcp'` OR untagged) → reject `Unauthenticated`,
 *     fail-closed per ch05 §4 ("untagged requests fail closed").
 *
 * TODO(T08): replace with `jose.jwtVerify` against a pre-warmed Cloudflare
 * Access JWKS, per ch05 §4 implementation block + §4.1 policy locks.
 */
function createJwtInterceptor(): Interceptor {
  return (next) => async (req) => {
    const transport = req.contextValues.get(transportTypeKey);
    if (transport === 'local-pipe') {
      return next(req);
    }
    // Fail-closed: untagged or remote-tcp without real JWT → reject.
    throw new ConnectError(
      'remote-ingress JWT verification not yet implemented (T08); reject fail-closed',
      Code.Unauthenticated,
    );
  };
}

/**
 * Migration-gate interceptor (ch02 §8 row "Migration-gate interceptor").
 * Mirrors the v0.3 envelope `migrationGateInterceptor` decision (envelope
 * version lives at `daemon/src/envelope/migration-gate-interceptor.ts`).
 *
 * Connect-side this PR does not yet have the supervisor-RPC carve-out
 * because the supervisor stays on the envelope (ch02 §6) — the only RPCs
 * served by Connect are data-plane. If a future RPC needs to bypass the
 * gate (e.g. a maintenance-mode `Ping`), extend the predicate here.
 */
function createMigrationGateInterceptor(opts: {
  isMigrationPending: () => boolean;
}): Interceptor {
  return (next) => async (req) => {
    if (opts.isMigrationPending()) {
      throw new ConnectError(
        `RPC ${req.method.name} rejected: SQLite migration in progress`,
        Code.FailedPrecondition,
      );
    }
    return next(req);
  };
}

/**
 * Hello-gate interceptor (ch02 §8 inheritance of v0.3 §3.4.1.f slot #0).
 *
 * Pre-handshake (helloAckKey === false), only methods on
 * {@link PRE_HANDSHAKE_ALLOWLIST} are admitted. Any other RPC is rejected
 * with {@link HELLO_REQUIRED_CODE} (== `Code.Unauthenticated`).
 */
function createHelloGateInterceptor(): Interceptor {
  return (next) => async (req) => {
    const handshaked = req.contextValues.get(helloAckKey) === true;
    if (handshaked) return next(req);
    if (PRE_HANDSHAKE_ALLOWLIST_SET.has(req.method.name)) return next(req);
    throw new ConnectError(
      `RPC ${req.method.name} rejected: daemon.hello handshake required first`,
      HELLO_REQUIRED_CODE,
    );
  };
}

/**
 * Deadline interceptor (ch02 §8 row "Per-frame deadline").
 *
 * T05 ships the chain slot only — the v0.3 envelope already owns deadline
 * resolution (`daemon/src/envelope/deadline-interceptor.ts`); when T08+ wires
 * the real Connect-side deadline reading the `x-ccsm-deadline-ms` header, it
 * will replace this stub. Stubbed as pass-through here so the chain ordering
 * test pins the slot.
 *
 * TODO(T08+): read `x-ccsm-deadline-ms` header (default 30s, clamp at 120s
 * per ch02 §8) and compose with `req.signal` via `AbortSignal.timeout`.
 */
function createDeadlineInterceptor(): Interceptor {
  return (next) => async (req) => next(req);
}

/**
 * Trace-id interceptor (ch02 §8 row "Trace-id ULID per envelope").
 *
 * Generates a ULID on entry and stores it under {@link traceIdKey} for
 * downstream handlers + log lines. Mirrors the v0.3 envelope
 * `x-ccsm-trace-id` propagation.
 */
function createTraceIdInterceptor(): Interceptor {
  return (next) => async (req) => {
    if (!req.contextValues.get(traceIdKey)) {
      req.contextValues.set(traceIdKey, ulid());
    }
    return next(req);
  };
}

// ---------------------------------------------------------------------------
// Chain assembly
// ---------------------------------------------------------------------------

export interface InterceptorChainOptions {
  readonly isMigrationPending: () => boolean;
  /**
   * Optional Listener A peer-cred interceptor wiring. When provided,
   * a peer-cred interceptor is inserted at slot #0 of the chain so it
   * runs BEFORE transport-tag — same-OS-user check is the gate that
   * justifies the local-pipe JWT bypass downstream. Omit on
   * remote-only Connect servers (Listener B carries its own JWT
   * trust; peer-cred has no meaning over TCP).
   */
  readonly peerCred?: PeerCredInterceptorOptions;
}

/**
 * Build the canonical interceptor stack in the spec-locked order:
 *
 *     [0] peer-cred       (frag-6-7 §6.1 — Listener A only; OPTIONAL slot,
 *                          inserted iff opts.peerCred is provided)
 *     [1] transport-tag    (ch05 §4 — positive enum tag, no-op decider in T05)
 *     [2] jwt              (ch05 §4 — placeholder; T08 lands real verify)
 *     [3] migration-gate   (ch02 §8 — block data-plane during migration)
 *     [4] hello-gate       (ch02 §8 — pre-handshake reject)
 *     [5] deadline         (ch02 §8 — placeholder; T08+ lands real reader)
 *     [6] trace-id         (ch02 §8 — ULID per request)
 *
 * Connect applies SERVER interceptors outermost-first per array order
 * (i.e. element 0 wraps element 1 wraps the handler). Peer-cred runs
 * outermost so a mismatched peer is rejected before any other slot
 * burns CPU on it.
 */
export function buildInterceptorChain(opts: InterceptorChainOptions): Interceptor[] {
  const chain: Interceptor[] = [];
  if (opts.peerCred !== undefined) {
    chain.push(createPeerCredInterceptor(opts.peerCred));
  }
  chain.push(
    createTransportTagInterceptor(),
    createJwtInterceptor(),
    createMigrationGateInterceptor(opts),
    createHelloGateInterceptor(),
    createDeadlineInterceptor(),
    createTraceIdInterceptor(),
  );
  return chain;
}

// ---------------------------------------------------------------------------
// Server lifecycle
// ---------------------------------------------------------------------------

export interface CreateConnectDataServerOptions {
  /**
   * Caller registers Connect services on the router. T05 PR ships this with
   * an empty function (no services); T06 will land `router.service(CcsmService, {…})`
   * here.
   */
  readonly registerRoutes: (router: ConnectRouter) => void;

  /** Migration-gate predicate. See {@link createMigrationGateInterceptor}. */
  readonly isMigrationPending: () => boolean;

  /**
   * Listener A peer-cred wiring. When provided:
   *   - The peer-cred interceptor is inserted at slot #0 of the chain.
   *   - Each request's contextValues is seeded from `peerCred.stash`
   *     (keyed by the underlying socket), so the interceptor sees the
   *     verdict the listener stamped at connection-accept time.
   *
   * Omit on Connect servers that are NOT fronted by Listener A
   * (Listener B carries JWT trust over remote TCP; peer-cred has no
   * meaning there).
   */
  readonly peerCred?: {
    readonly stash: PeerCredStash;
    readonly logger?: PeerCredInterceptorOptions['logger'];
  };
}

export interface ConnectDataServer {
  /** The Node-style HTTP/2 request handler produced by `connectNodeAdapter`. */
  readonly handler: ReturnType<typeof connectNodeAdapter>;

  /**
   * Bind the Connect router to a fresh HTTP/2 server on the given address.
   * Returns the bound port (useful when `port: 0` requests an ephemeral one).
   */
  listen(opts: { host: string; port: number }): Promise<number>;

  /**
   * Hand a pre-accepted Duplex socket to the underlying HTTP/2 server. The
   * data-socket integration (T12 / T19 wave) calls this AFTER it has peeked
   * the HTTP/2 preface on the connection. The `transportType` argument is
   * stamped on every request's `contextValues` via the adapter's
   * `contextValues` factory so the JWT interceptor can apply the local bypass.
   *
   * NOT live in T05: callers MAY use this to build coexistence wiring in
   * follow-up PRs. Tested here only at the surface level.
   */
  attachSocket(socket: Duplex, transportType: 'local-pipe' | 'remote-tcp'): void;

  /** Close the HTTP/2 server (if `listen()` was called) and stop accepting new sockets. */
  close(): Promise<void>;
}

/**
 * Create a Connect-RPC server bound to the daemon data-socket surface.
 *
 * Architecture:
 *   - One {@link ConnectRouter} with the spec-locked interceptor chain.
 *   - One Node HTTP/2 server that calls the Connect adapter. The adapter's
 *     `contextValues` factory reads a per-socket transport-tag stash (set by
 *     `attachSocket`) and stamps {@link transportTypeKey} on each request.
 *   - For pre-accepted sockets (the data-socket case) we route via
 *     `Http2Server.emit('connection', socket)` — Node's documented mechanism.
 */
export function createConnectDataServer(
  opts: CreateConnectDataServerOptions,
): ConnectDataServer {
  // Per-socket transport-tag stash. The adapter's contextValues factory looks
  // up the originating socket and reads its tag. This avoids reading any
  // header (per ch05 §4 — header reads would let an attacker spoof the tag).
  const socketTags = new WeakMap<Duplex, 'local-pipe' | 'remote-tcp'>();

  const interceptors = buildInterceptorChain({
    isMigrationPending: opts.isMigrationPending,
    peerCred: opts.peerCred ? { logger: opts.peerCred.logger } : undefined,
  });

  const handler = connectNodeAdapter({
    routes: opts.registerRoutes,
    interceptors,
    contextValues: (req) => {
      // Note: we use createContextValues from @connectrpc/connect, accessed
      // via the adapter's contract — pass an existing values object back.
      // The adapter calls our factory once per request. We construct a fresh
      // values map and seed the transport tag from the socket stash.
      const values = lazyCreateContextValues();
      const sock = (req as unknown as { socket?: Duplex }).socket;
      const tag = sock ? socketTags.get(sock) : undefined;
      if (tag !== undefined) {
        values.set(transportTypeKey, tag);
      }
      // Seed the Listener A peer-cred verdict from the per-socket stash
      // so the slot #0 interceptor can decide pass/reject before any
      // other interceptor runs. Absent verdict → undefined → interceptor
      // fail-closes (per listenerA.ts §3 contract).
      if (sock && opts.peerCred) {
        const verdict = opts.peerCred.stash.get(sock);
        if (verdict !== undefined) {
          values.set(listenerAPeerCredVerdictKey, verdict);
        }
      }
      return values;
    },
  });

  let httpServer: http2.Http2Server | undefined;

  return {
    handler,

    async listen({ host, port }: { host: string; port: number }): Promise<number> {
      if (httpServer) {
        throw new Error('Connect data server already listening');
      }
      httpServer = http2.createServer();
      // Wire the Connect Node adapter as the request listener. http2 emits
      // 'request' for HTTP/2 streams that carry a request (i.e. with method+path).
      httpServer.on('request', handler);
      await new Promise<void>((resolve, reject) => {
        const onError = (err: Error): void => {
          httpServer!.removeListener('listening', onListening);
          reject(err);
        };
        const onListening = (): void => {
          httpServer!.removeListener('error', onError);
          resolve();
        };
        httpServer!.once('error', onError);
        httpServer!.once('listening', onListening);
        httpServer!.listen(port, host);
      });
      const addr = httpServer.address();
      if (typeof addr === 'object' && addr !== null && 'port' in addr) {
        return addr.port;
      }
      return port;
    },

    attachSocket(socket: Duplex, transportType: 'local-pipe' | 'remote-tcp'): void {
      if (!httpServer) {
        // We tolerate attach-before-listen in T05 because the data-socket
        // wiring may want to share a single HTTP/2 server across the local
        // pipe + remote TCP listeners. T19 wave will lock this down.
        socketTags.set(socket, transportType);
        return;
      }
      socketTags.set(socket, transportType);
      // Hand the pre-accepted socket to the HTTP/2 server. Node will run the
      // HTTP/2 preface check and dispatch streams to the 'request' handler.
      httpServer.emit('connection', socket);
    },

    async close(): Promise<void> {
      if (!httpServer) return;
      await new Promise<void>((resolve) => {
        httpServer!.close(() => resolve());
      });
      httpServer = undefined;
    },
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// `createContextValues` lives in @connectrpc/connect/protocol but re-exported
// at the package root. We import lazily to avoid a circular type dependency
// when this module is consumed by the test harness.
import { createContextValues as _createContextValues } from '@connectrpc/connect';

function lazyCreateContextValues(): ReturnType<typeof _createContextValues> {
  return _createContextValues();
}

// Suppress an unused-import warning for the universalRequestFromNodeRequest
// re-export in case esbuild treeshaking needs it during bundling spike.
void universalRequestFromNodeRequest;
